### ISSUE TITLE
Please remove bugsense - its proprietary software

### ISSUE THREAD

**Issue by huks481** [tinfoilhat/tinfoil-sms#29]
Please remove bugsense. This is proprietary software!

**Comment by gnu-user** [comment]
Thanks for your feedback, BugSense was open source when we started using it, but for some reason it now appears that the source code for their BugSense SDK is no longer available, perhaps this has occurred in the time since they were bought out by Splunk. We've checked and it appears that they're still honouring their free accounts (with no limits) for open source projects, such as ours, which was one of the reasons we initially decided to use BugSense for bug tracking (it was open source and they offered accounts for open source projects without limitations). However, in the mean time we will still be using it for our beta process until we can find an open source alternative that we can integrate into the project.

**Comment by huks481** [comment]
Please reopen the bug again. It is not fixed.
When would you remove this? I would like to try out the software. Or please make a version without proprietary software.

thanks

**Comment by dalb8** [comment]
That version of bugsense was free software and then the source code disappeared. I'm not sure if this means it's proprietary, but I don't know where to find the source code.

**Comment by huks481** [comment]
That mean the software licence have _changed_. You had have to fork the Software _before_ this licence change and use from there on your forked software. Now you are using proprietary software.
Please remove this part. Its not relevant for the functionality.

**Comment by dataBaseError** [comment]
Hello, thanks again for your feedback. We contacted Bugsense to investigate the concerns you raised about software license used for Bugsense. we've released a version of Tinfoil-SMS that does not include bugsense which can be found at: https://github.com/tinfoilhat/tinfoil-sms/releases/tag/v1.2.6-fdroid. The next release of Tinfoil-SMS (v1.3.0) will be coming out soon and we plan to also release v1.3.0-fdroid at the same time.
