### ISSUE TITLE
Fail to decrypt on receive. 

### ISSUE THREAD

**Issue by dataBaseError** [tinfoilhat/tinfoil-sms#4]
There is a problem with the encryption library when it comes to encrypting and decrypting messages.
This is repeated by:
- Set up two devices
- Exchange keys between the devices
- Once the key exchange has finished, attempt to send an encrypted (send a message) from 1 contact to the other.
- The contact that receives the message will notify that the message failed to decrypt. 
- The log message should look similar to the log file committed.

Please see https://github.com/tinfoilhat/tinfoil-sms/blob/master/branches/tinfoil-sms/logcat_secret_messages.log for the log file.

**Comment by gnu-user** [comment]
This issue was resolved in 925ec75b11acd53cd6f40784cc00b3c20c17b761 the reason the encryption was failing is due to the fact that the encrypted messages were not being encoded as Base64. Android (and perhaps the SMS protocol itself), were corrupting the actual text being sent unless it was encoded with Base64.
