### ISSUE TITLE
Switching from TextSecure to Tinfoil-SMS

### ISSUE THREAD

**Issue by SecUpwN** [tinfoilhat/tinfoil-sms#70]
Hi there, @tinfoilhat! I have just been reading about your awesome App in a great [article on Kuketz IT-Security Blog](http://www.kuketz-blog.de/tinfoil-sms-und-cameonet-alternativen-zu-textsecure/) and am now monitoring development since I very much like the very fact that you take security **extremely serious** while having this project under GPL and welcome developer involvement.

Although I still love [TextSecure](https://github.com/WhisperSystems/TextSecure) and keep recommending it to friends, I will likely be forced to switch to a Messenger of same if not higher security level since they are very likely going to nuke SMS as discussed in their Issue https://github.com/WhisperSystems/TextSecure/issues/1762 and their internal development mailing lists. Let me say this ot make you proud a little: Your messnger is in fact the first one I consider switching to. Very seldom!

Hence this Issue: How about importing TextSecure keys? Are you going to support Websockets like discussed in https://github.com/WhisperSystems/TextSecure/issues/1000? Please make a transition from TextSecure to Tinfoil-SMS as hassle-free as possible and ensure that Tinfoil-SMS can auto-detect TextSecure to guide the user while making the switch. Rock this and don't let yourself get discouraged! I bet other security enthusiasts like @kuba86 or @c33s will soon start spreading the word. May the pwnsauce be with you!

**Comment by gnu-user** [comment]
Hi,

We considered the option to import textsecure keys and it may be feasible to implement, however we would recommend that it may just be easier to perform new key exchanges with your contacts for optimal security.

Tinfoil-SMS actually uses a form of personal certificate authority, whereby you and a contact come up with shared secrets which are used to sign and validate the keys exchanged prior to the key exchange taking place. This is pretty much the only way to securely exchange keys and mitigate the risk of a man-in-the-middle attack.

As for detecting text-secure, unfortunately it is not easy for us to add that feature as we do not integrate with their protocol and in fact Tinfoil-SMS has no easily identifiable protocol in order to make it more difficult to detect.

For a full explanation/writeup please see: http://www.reddit.com/r/crypto/comments/1w5iap/tinfoilsms_a_new_secure_text_messaging_app_for/

**Comment by SecUpwN** [comment]
Good morning @gnu-user, thanks for not forgetting me here. Your explanation is quite thorough and thought-through, yet I have some questions: When a user has to sit down with another users and come up with a shared secret, how am I going to rule out a MITM attack if such is not possible due to the distance between each other? Considering the fact that it has been extremely difficult for me to convince most of my friends to use TextSecure, I see that telling them to switch to Tinfoil-SMS is..well.. not going to happen yet. Hence, I consider implementation of importing TextSecure keys still very important.

**Comment by gnu-user** [comment]
@SecUpwN That's a good point you've made, I guess we could make the shared secrets optional and perhaps add some simplifications so that it automatically accepts keys from contacts. In the event of that you would only need to convince your friends to install the app and then after they have installed it you could simply just open a chat with them and click the "Initiate key exchange" and it would automatically exchange the keys.

At this point adding support to import TextSecure keys would still require them to export their TextSecure keys then manually one by one import your keys. I think it would be easier in the above scenario to just get them to install the app, you initiate the key exchange with them, and then the app just automatically adds you as one of their trusted contacts.

**Comment by SecUpwN** [comment]
> That's a good point you've made, I guess we could make the shared secrets optional and perhaps add some simplifications so that it automatically accepts keys from contacts.

Thanks. would it be possible to enable Tinfoil-SMS to work vice-versa? That would be the **ultimate enhancement** and would mean even if TextSecure finallyy ditched encrypted SMS, noone would need to care or worry about missing encryption since Tinfoil-SMS would handle it! ;-) Or isn't this possible?

**Comment by gnu-user** [comment]
By vice-versa do you mean support to accept Text-Secure keys if a message is received from a contact? If so then at the current time it's not possible, and because we do not use the same protocol as text secure would take a lot of effort to support.

I think the easiest would just be my above suggestion, and just have everyone change apps and you simply send each one of them a key exchange.

**Comment by SecUpwN** [comment]
Thanks for your recommendations @gnu-user. I liked this project a lot, but since it seems to be unmaintained and halted in development, I switched to [SMSSecure](https://github.com/SMSSecure/SMSSecure/), an awesome fork of the TextSecure project, but **with SMS encryption** and covering this in their [Issue #16](https://github.com/SMSSecure/SMSSecure/pull/16). See www.smssecure.org for more information. Closing this Issue since all my friends switched to their app too. Stay well and good luck!
